name: On Push Main

on:
  push:
    branches:
      - main

env:
  EXPORT_PATH: export/html5
      
jobs:
  on-push:
    runs-on: ubuntu-24.04
    container:
      image: barichello/godot-ci:4.7.1-stable
    steps:
      - uses: actions/checkout@v4

      - name: Import Godot project
        # required for GUT
        shell: bash
        run: |
          set -euo pipefail
          godot --headless --path . --import

      - name: Run GUT tests
        shell: bash
        run: |
          set -euo pipefail
          godot --headless --path . -s addons/gut/gut_cmdln.gd -gexit 2>&1 | tee gut.log
          if grep -q 'Some GUT class_names have not been imported' gut.log; then
            echo 'GUT failed because required classes were not imported.'
            exit 1
          fi

      - name: Build Godot project
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p ${EXPORT_PATH}
          godot --headless --path . --export-release "Web" ${EXPORT_PATH}/index.html

      - name: Push to itch.io
        shell: bash
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: |
          set -euo pipefail
          butler push ${EXPORT_PATH}/ jsonstache/stabby-game:html5
